# societies_data.py — shared society info, used by Recommendation.py and Favourites.py

SOCIETIES = [
    {
        "name": "TechNeeds",
        "domain": "AI/ML, DSA, Web Dev, UI/UX",
        "description": "Active technical society organizing tech events and workshops throughout the year.",
        "activities": "InnoVortex Hackathon, SSSC Summer Cohort, 21 Days of Code, workshops",
        "skills_required": "Enthusiasm to learn and contribute consistently",
        "commitment_per_week": 6,
        "commitment_text": "2-10 hrs (varies by event)",
        "recruitment_month": "August (sometimes June/July)",
        "instagram": "https://www.instagram.com/techneeds_igdtuw_/",
        "website": None,
        "match_pct": 85
    },
    {
        "name": "AssetMerkle",
        "domain": "Web3, Blockchain, Decentralized Tech",
        "description": "IGDTUW's only Web3/blockchain society focused on awareness and community building.",
        "activities": "AM Hacks (flagship hackathon), Web3 Week, Community Meetups",
        "skills_required": "Basic coding, Event management, Communication, Canva/design",
        "commitment_per_week": 2,
        "commitment_text": "~2 hrs/week avg (more during events)",
        "recruitment_month": "End of August (1st & 2nd year)",
        "instagram": "https://www.instagram.com/assetmerkle.igdtuw/",
        "website": None,
        "match_pct": 72
    },
    {
        "name": "IEEE IGDTUW",
        "domain": "Electrical, Electronics, CS, AI, Blockchain, AR/VR",
        "description": "Aligns with IEEE WIE global network; promotes women in engineering and STEM.",
        "activities": "Speaker sessions, hands-on workshops on AR/VR, 3D printing, drone making",
        "skills_required": "Interest in technical research, hardware, emerging tech (AR/VR)",
        "commitment_per_week": 5,
        "commitment_text": "High during flagship weeks; none during exams",
        "recruitment_month": "August-September",
        "instagram": "https://www.instagram.com/ieeeigdtuw/",
        "website": None,
        "match_pct": 90
    },
    {
        "name": "Nirvana",
        "domain": "UI/UX Design, Graphic Design",
        "description": "Design club focused on design thinking before students transition into development.",
        "activities": "Cohorts, hackathons, workshops, quizzes, design showcases",
        "skills_required": "Basic Canva proficiency, colour theory, curiosity to learn",
        "commitment_per_week": 4.5,
        "commitment_text": "~4-5 hrs/week during cohorts",
        "recruitment_month": "Induction period",
        "instagram": "https://www.instagram.com/designclubigdtuw/",
        "website": None,
        "match_pct": 78
    },
    {
        "name": "Tarannum",
        "domain": "Music - Indian Classical, Western, Rock Band, PR & Media",
        "description": "Musical society with 3 performance teams and PR and Media team.",
        "activities": "Riyaz sessions, Garba Night, Halloween events, flash mobs, inter-college competitions",
        "skills_required": "Passion for music; good voice/instrument skills; PR/Media skills",
        "commitment_per_week": 12,
        "commitment_text": "Varies — regular riyaz + increased during events",
        "recruitment_month": "August",
        "instagram": "https://www.instagram.com/tarannum.igdtuw/",
        "website": None,
        "match_pct": 60
    },
    {
        "name": "Rahnuma",
        "domain": "Dramatics, Theatre, Street Play, Public Speaking",
        "description": "Dramatics society that teaches life lessons through theatre and street plays.",
        "activities": "Aaghaz Street Play, Bachpan-e-Karvaan (Children's Day event)",
        "skills_required": "Eagerness to learn; no prior acting experience required",
        "commitment_per_week": 3,
        "commitment_text": "2-3 hrs/day (alternating timings)",
        "recruitment_month": "Mid August - Early September",
        "instagram": "https://www.instagram.com/rahnuma_igdtuw/",
        "website": None,
        "match_pct": 55
    },
    {
        "name": "Hypnotics",
        "domain": "Dance, Choreography, Cultural Events",
        "description": "Official dance society of IGDTUW — platform for dance skill-building and competitions.",
        "activities": "Dance workshops, inter-college competitions, cultural fest performances",
        "skills_required": "Passion for dance, dedication, teamwork, creativity",
        "commitment_per_week": 9,
        "commitment_text": "6-12 hrs/week",
        "recruitment_month": "August-September",
        "instagram": "https://www.instagram.com/hypnotics_igdtuw/",
        "website": None,
        "match_pct": 50
    },
    {
        "name": "Finivesta",
        "domain": "Finance, Economics, Financial Literacy, Stock Markets",
        "description": "Women-led finance and economics society promoting financial literacy through events.",
        "activities": "Payload, Bidding Blitz, Finopoly, Money Masterclass, FinWeek",
        "skills_required": "Basic finance and economics understanding; enthusiasm, proactiveness",
        "commitment_per_week": 2.5,
        "commitment_text": "2-3 hrs/week",
        "recruitment_month": "Late September - Early October",
        "instagram": "https://www.instagram.com/finivesta_igdtuw/",
        "website": None,
        "match_pct": 65
    },
    {
        "name": "MSC IGDTUW",
        "domain": "Tech Education, AI/DS, Skill Development, Networking",
        "description": "Microsoft Learn Student Ambassador chapter empowering women technologists.",
        "activities": "Hackathons, webinars, Summer Bootcamp, Networking Nights, Microsoft office sessions",
        "skills_required": "Passion for tech, interest in leadership and community building",
        "commitment_per_week": 2,
        "commitment_text": "1-2 hrs/week",
        "recruitment_month": "June (1st years)",
        "instagram": "https://www.instagram.com/msc.igdtuw/",
        "website": None,
        "match_pct": 88
    },
    {
        "name": "SOCH",
        "domain": "Art, Writing, Management, PR & Marketing",
        "description": "Art and writing society providing a creative platform for expression and storytelling.",
        "activities": "Art and writing competitions, slam poetry, creative workshops",
        "skills_required": "Sketching, graphic design, creative writing, poetry, event management",
        "commitment_per_week": 3,
        "commitment_text": "2-4 hrs/week",
        "recruitment_month": "Beginning of academic session",
        "instagram": None,
        "website": None,
        "match_pct": 62
    },
    {
        "name": "B.H.A.V",
        "domain": "Public Speaking, Debate, MUN, Creative Writing",
        "description": "Creative society focused on public speaking and literary exposure.",
        "activities": "Aarohan (annual lit fest), IGDTUMUN, mock Youth Parliaments",
        "skills_required": "Basic Hindi and English, awareness of current topics",
        "commitment_per_week": 2,
        "commitment_text": "Monthly/event-based",
        "recruitment_month": "August-October",
        "instagram": None,
        "website": None,
        "match_pct": 58
    },
    {
        "name": "ACM Student Chapter",
        "domain": "Competitive Programming, ML/AI, Data Science, Open Source",
        "description": "One of IGDTUW's oldest technical societies; fosters learning in tech and innovation.",
        "activities": "ACM Research Internship, workshops, bootcamps, hackathons, open-source initiatives",
        "skills_required": "Enthusiasm to learn; teamwork; basic domain knowledge preferred",
        "commitment_per_week": 3,
        "commitment_text": "2-3 hrs/week (reduced during exams)",
        "recruitment_month": "August-September",
        "instagram": "https://www.instagram.com/acm_igdtuw/",
        "website": None,
        "match_pct": 92
    },
    {
        "name": "Rotaract Club",
        "domain": "Community Service, Women Empowerment, Mental Health",
        "description": "Student-led organization for community service, leadership, and global networking.",
        "activities": "Dear Zindagi (mental health fest), blood donation camps, NGO outreach",
        "skills_required": "Communication, leadership, event planning; no prior experience needed",
        "commitment_per_week": 2,
        "commitment_text": "Flexible/volunteer-based",
        "recruitment_month": "August-September",
        "instagram": None,
        "website": None,
        "match_pct": 70
    },
    {
        "name": "SWE IGDTUW",
        "domain": "Technical Workshops, Leadership, Industry Networking",
        "description": "Student chapter of Society of Women Engineers empowering women in engineering.",
        "activities": "Workshops, bootcamps, expert talks, mentorship programs, hackathons",
        "skills_required": "Teamwork, communication, interest in tech and leadership",
        "commitment_per_week": 4,
        "commitment_text": "Regular: 2-4 hrs/week; Core: 4-8 hrs/week",
        "recruitment_month": "August-September",
        "instagram": None,
        "website": None,
        "match_pct": 80
    },
    {
        "name": "ASME IGDTUW",
        "domain": "AI & Computer Vision, CAD, Robotics, Embedded Systems",
        "description": "Student-led technical society focused on hands-on learning and industry exposure.",
        "activities": "Technical workshops, expert talks, industry sessions, project-based learning",
        "skills_required": "Curiosity and willingness to learn; prior experience is a plus",
        "commitment_per_week": 3.5,
        "commitment_text": "2-5 hrs/week (more during events)",
        "recruitment_month": "August-September",
        "instagram": None,
        "website": None,
        "match_pct": 75
    },
    {
        "name": "CodeBenders",
        "domain": "DSA, Competitive Programming, Open Source, Career Prep",
        "description": "Technical society dedicated to building a strong tech community through mentorship.",
        "activities": "DSA Bootcamps, Open Source Week, resume building, pre-placement prep",
        "skills_required": "Basic programming; Figma/Canva for design; communication for sponsorship",
        "commitment_per_week": 4,
        "commitment_text": "3-5 hrs/week (more during events)",
        "recruitment_month": "September-October",
        "instagram": None,
        "website": None,
        "match_pct": 87
    },
    {
        "name": "E-Cell",
        "domain": "Entrepreneurship, Innovation, Startup Awareness, Leadership",
        "description": "Student-led entrepreneurship cell fostering innovation and startup culture.",
        "activities": "Founder talks, expert workshops, ideathons, case study competitions",
        "skills_required": "Communication, teamwork, leadership, problem-solving, organizational skills",
        "commitment_per_week": 13.5,
        "commitment_text": "12-15 hrs/week (highest commitment)",
        "recruitment_month": "August-September",
        "instagram": None,
        "website": None,
        "match_pct": 68
    },
    {
        "name": "Enactus",
        "domain": "Social Entrepreneurship, Community Development, Sustainability",
        "description": "Social entrepreneurship society building scalable solutions for real-world challenges.",
        "activities": "Enactova (National Business Plan Competition), Innovation Fair, community outreach",
        "skills_required": "Communication, teamwork, problem-solving, creativity, research skills",
        "commitment_per_week": 4,
        "commitment_text": "3-5 hrs/week (more during major events)",
        "recruitment_month": "August-September",
        "instagram": None,
        "website": None,
        "match_pct": 73
    },
]